parameters:
#    byte_history_connection.example.class: ByteHistory\ConnectionBundle\Example

services:
#    byte_history_connection.example:
#        class: %byte_history_connection.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
