parameters:
#    byte_history_start.example.class: ByteHistory\StartBundle\Example

services:
#    byte_history_start.example:
#        class: %byte_history_start.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
