partner_index:
    pattern:  /partner
    defaults: { _controller: ByteHistoryPartnerBundle:Default:index }
    
partner_add:
    pattern:  /partner/add
    defaults: { _controller: ByteHistoryPartnerBundle:Default:add }
