parameters:
#    byte_history_partner.example.class: ByteHistory\PartnerBundle\Example

services:
#    byte_history_partner.example:
#        class: %byte_history_partner.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
